version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9.1
        auth:
          username: buscedv
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: pip install -r requirements.txt
  test:
    docker:
      - image: circleci/python:3.9.1
        auth:
          username: buscedv
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: python test_ask.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test



